// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package hm

var TableNames = struct {
	Roles         string
	Subscriptions string
	Tenants       string
	Users         string
}{
	Roles:         "roles",
	Subscriptions: "subscriptions",
	Tenants:       "tenants",
	Users:         "users",
}
