// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package hm

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("Roles", testRolesUpsert)

	t.Run("Subscriptions", testSubscriptionsUpsert)

	t.Run("Tenants", testTenantsUpsert)

	t.Run("Users", testUsersUpsert)
}
